(define (problem p07-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 2.947)
    (= (x ROBOT2) 6.641)
    (= (x ROBOT3) 2.483)
    (= (x ROBOT4) 7.824)
    (= (x ROBOT5) 8.311)
    (= (x ROBOT6) 5.735)
    (= (x ROBOT7) 9.593)
    (= (x TARGET) 4.656)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
    )
  )
)
