(define (problem p07-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 9.767)
    (= (x ROBOT2) 0.493)
    (= (x ROBOT3) 5.616)
    (= (x ROBOT4) 1.848)
    (= (x ROBOT5) 1.149)
    (= (x ROBOT6) 2.765)
    (= (x ROBOT7) 3.799)
    (= (x TARGET) 2.490)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
    )
  )
)
