(define (problem p7)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT10 ROBOT20 ROBOT30 ROBOT40 ROBOT50 - robot 
            TARGET - target)
  (:init
    (is_robot ROBOT1) (is_robot ROBOT2) (is_robot ROBOT3) 
    (is_robot ROBOT4) (is_robot ROBOT5)
    (is_robot ROBOT10) (is_robot ROBOT20) (is_robot ROBOT30) 
    (is_robot ROBOT40) (is_robot ROBOT50)
    (is_target TARGET)
    (= (x ROBOT1) 0)
    (= (x ROBOT2) 1)
    (= (x ROBOT3) 2)
    (= (x ROBOT4) 3)
    (= (x ROBOT5) 3)
    (= (x ROBOT10) 2)
    (= (x ROBOT20) 3)
    (= (x ROBOT30) 2)
    (= (x ROBOT40) 3)
    (= (x ROBOT50) 6)
    (= (x TARGET) 0)
  )
  (:goal
    (and
       (= (x ROBOT1) (x TARGET)) (= (x ROBOT2) (x TARGET)) 
       (= (x ROBOT3) (x TARGET)) (= (x ROBOT4) (x TARGET)) 
       (= (x ROBOT5) (x TARGET)) 
       (= (x ROBOT10) (x TARGET)) (= (x ROBOT20) (x TARGET)) 
       (= (x ROBOT30) (x TARGET)) (= (x ROBOT40) (x TARGET)) 
       (= (x ROBOT50) (x TARGET)) 
    )
  )
)