(define (problem p08-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 3.610)
    (= (x ROBOT2) 3.879)
    (= (x ROBOT3) 0.573)
    (= (x ROBOT4) 9.424)
    (= (x ROBOT5) 8.931)
    (= (x ROBOT6) 3.602)
    (= (x ROBOT7) 6.241)
    (= (x ROBOT8) 0.239)
    (= (x TARGET) 2.115)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
    )
  )
)
