(define (problem p08-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 7.912)
    (= (x ROBOT2) 1.215)
    (= (x ROBOT3) 9.791)
    (= (x ROBOT4) 6.641)
    (= (x ROBOT5) 5.335)
    (= (x ROBOT6) 4.737)
    (= (x ROBOT7) 8.084)
    (= (x ROBOT8) 2.993)
    (= (x TARGET) 8.622)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
    )
  )
)
