(define (problem p09-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 0.315)
    (= (x ROBOT2) 2.455)
    (= (x ROBOT3) 9.940)
    (= (x ROBOT4) 5.204)
    (= (x ROBOT5) 0.020)
    (= (x ROBOT6) 6.712)
    (= (x ROBOT7) 3.698)
    (= (x ROBOT8) 0.972)
    (= (x ROBOT9) 9.342)
    (= (x TARGET) 6.547)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (x ROBOT9) (x TARGET))
    )
  )
)
