(define (problem p09-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 4.286)
    (= (x ROBOT2) 6.908)
    (= (x ROBOT3) 9.786)
    (= (x ROBOT4) 7.661)
    (= (x ROBOT5) 4.602)
    (= (x ROBOT6) 9.096)
    (= (x ROBOT7) 7.554)
    (= (x ROBOT8) 3.288)
    (= (x ROBOT9) 3.742)
    (= (x TARGET) 1.794)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (x ROBOT9) (x TARGET))
    )
  )
)
