(define (problem p10-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 4.801)
    (= (x ROBOT2) 2.733)
    (= (x ROBOT3) 4.955)
    (= (x ROBOT4) 2.635)
    (= (x ROBOT5) 1.993)
    (= (x ROBOT6) 8.982)
    (= (x ROBOT7) 6.119)
    (= (x ROBOT8) 0.874)
    (= (x ROBOT9) 3.410)
    (= (x ROBOT10) 0.704)
    (= (x TARGET) 6.419)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (x ROBOT10) (x TARGET))
    )
  )
)
