(define (problem p10-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 3.672)
    (= (x ROBOT2) 0.566)
    (= (x ROBOT3) 0.719)
    (= (x ROBOT4) 4.381)
    (= (x ROBOT5) 9.848)
    (= (x ROBOT6) 2.922)
    (= (x ROBOT7) 9.220)
    (= (x ROBOT8) 1.161)
    (= (x ROBOT9) 8.157)
    (= (x ROBOT10) 1.276)
    (= (x TARGET) 3.686)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (x ROBOT10) (x TARGET))
    )
  )
)
