(define (problem p10-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 9.991)
    (= (x ROBOT2) 6.499)
    (= (x ROBOT3) 4.098)
    (= (x ROBOT4) 6.743)
    (= (x ROBOT5) 0.990)
    (= (x ROBOT6) 5.389)
    (= (x ROBOT7) 6.172)
    (= (x ROBOT8) 7.470)
    (= (x ROBOT9) 9.181)
    (= (x ROBOT10) 0.595)
    (= (x TARGET) 5.795)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (x ROBOT10) (x TARGET))
    )
  )
)
