(define (problem p27)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 9.0)
    (= (x ROBOT2) 4.0)
    (= (x ROBOT3) 10.0)
    (= (x ROBOT4) 2.0)
    (= (x ROBOT5) 10.0)
    (= (x ROBOT6) 2.0)
    (= (x TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
    )
  )
)
