(define (problem p38)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 4.0)
    (= (x ROBOT2) 4.0)
    (= (x ROBOT3) 9.0)
    (= (x ROBOT4) 1.0)
    (= (x ROBOT5) 5.0)
    (= (x ROBOT6) 5.0)
    (= (x ROBOT7) 1.0)
    (= (x ROBOT8) 7.0)
    (= (x TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (x ROBOT8) (x TARGET))
    )
  )
)
