(define (problem p2)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_target TARGET)
    (= (x ROBOT1) 2) (= (y ROBOT1) 3)
    (= (x ROBOT2) 1) (= (y ROBOT2) 4)
    (= (x TARGET) 0) (= (y TARGET) 0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
    )
  )
)