(define (problem p04-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_target TARGET)
    (= (x ROBOT1) 0.140)
    (= (y ROBOT1) 1.502)
    (= (x ROBOT2) 2.424)
    (= (y ROBOT2) 2.328)
    (= (x ROBOT3) 1.473)
    (= (y ROBOT3) 3.321)
    (= (x ROBOT4) 1.242)
    (= (y ROBOT4) 3.912)
    (= (x TARGET) 0.613)
    (= (y TARGET) 2.798)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
    )
  )
)
