(define (problem p04-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_target TARGET)
    (= (x ROBOT1) 4.080)
    (= (y ROBOT1) 2.402)
    (= (x ROBOT2) 0.630)
    (= (y ROBOT2) 0.570)
    (= (x ROBOT3) 4.250)
    (= (y ROBOT3) 3.558)
    (= (x ROBOT4) 1.277)
    (= (y ROBOT4) 2.573)
    (= (x TARGET) 0.222)
    (= (y TARGET) 2.666)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
    )
  )
)
