(define (problem p04-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_target TARGET)
    (= (x ROBOT1) 2.161)
    (= (y ROBOT1) 2.699)
    (= (x ROBOT2) 1.118)
    (= (y ROBOT2) 0.134)
    (= (x ROBOT3) 3.025)
    (= (y ROBOT3) 4.133)
    (= (x ROBOT4) 1.677)
    (= (y ROBOT4) 1.890)
    (= (x TARGET) 0.133)
    (= (y TARGET) 2.470)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
    )
  )
)
