(define (problem p05-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_target TARGET)
    (= (x ROBOT1) 1.801)
    (= (y ROBOT1) 3.120)
    (= (x ROBOT2) 0.120)
    (= (y ROBOT2) 1.888)
    (= (x ROBOT3) 2.978)
    (= (y ROBOT3) 2.117)
    (= (x ROBOT4) 0.587)
    (= (y ROBOT4) 2.404)
    (= (x ROBOT5) 1.232)
    (= (y ROBOT5) 3.132)
    (= (x TARGET) 4.712)
    (= (y TARGET) 4.465)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
    )
  )
)
