(define (problem p05-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_target TARGET)
    (= (x ROBOT1) 4.018)
    (= (y ROBOT1) 3.333)
    (= (x ROBOT2) 4.820)
    (= (y ROBOT2) 2.427)
    (= (x ROBOT3) 3.788)
    (= (y ROBOT3) 4.467)
    (= (x ROBOT4) 2.624)
    (= (y ROBOT4) 2.473)
    (= (x ROBOT5) 0.786)
    (= (y ROBOT5) 4.685)
    (= (x TARGET) 1.410)
    (= (y TARGET) 4.617)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
    )
  )
)
