(define (problem p05-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_target TARGET)
    (= (x ROBOT1) 1.155)
    (= (y ROBOT1) 3.915)
    (= (x ROBOT2) 1.443)
    (= (y ROBOT2) 3.372)
    (= (x ROBOT3) 3.172)
    (= (y ROBOT3) 4.707)
    (= (x ROBOT4) 4.073)
    (= (y ROBOT4) 4.757)
    (= (x ROBOT5) 1.081)
    (= (y ROBOT5) 0.191)
    (= (x TARGET) 1.674)
    (= (y TARGET) 0.985)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
    )
  )
)
