(define (problem p05-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_target TARGET)
    (= (x ROBOT1) 4.797)
    (= (y ROBOT1) 1.245)
    (= (x ROBOT2) 4.884)
    (= (y ROBOT2) 0.246)
    (= (x ROBOT3) 2.808)
    (= (y ROBOT3) 0.924)
    (= (x ROBOT4) 0.574)
    (= (y ROBOT4) 1.382)
    (= (x ROBOT5) 1.900)
    (= (y ROBOT5) 0.008)
    (= (x TARGET) 4.155)
    (= (y TARGET) 2.867)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
    )
  )
)
