(define (problem p05-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_target TARGET)
    (= (x ROBOT1) 0.437)
    (= (y ROBOT1) 0.729)
    (= (x ROBOT2) 3.520)
    (= (y ROBOT2) 2.200)
    (= (x ROBOT3) 1.287)
    (= (y ROBOT3) 2.492)
    (= (x ROBOT4) 1.057)
    (= (y ROBOT4) 1.805)
    (= (x ROBOT5) 1.940)
    (= (y ROBOT5) 0.287)
    (= (x TARGET) 0.150)
    (= (y TARGET) 0.976)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
    )
  )
)
