(define (problem p5)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_target TARGET)
    (= (x ROBOT1) 13) (= (y ROBOT1) 5)
    (= (x ROBOT2) 2) (= (y ROBOT2) 4)
    (= (x ROBOT3) 5) (= (y ROBOT3) 2)
    (= (x ROBOT4) 2) (= (y ROBOT4) 2)
    (= (x TARGET) 0) (= (y TARGET) 0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
    )
  )
)