(define (problem p06-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 4.311)
    (= (y ROBOT1) 3.956)
    (= (x ROBOT2) 0.607)
    (= (y ROBOT2) 4.896)
    (= (x ROBOT3) 3.320)
    (= (y ROBOT3) 2.667)
    (= (x ROBOT4) 2.368)
    (= (y ROBOT4) 4.042)
    (= (x ROBOT5) 1.496)
    (= (y ROBOT5) 3.341)
    (= (x ROBOT6) 1.934)
    (= (y ROBOT6) 2.798)
    (= (x TARGET) 3.461)
    (= (y TARGET) 2.747)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
    )
  )
)
