(define (problem p06-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 2.602)
    (= (y ROBOT1) 0.010)
    (= (x ROBOT2) 3.356)
    (= (y ROBOT2) 1.849)
    (= (x ROBOT3) 0.486)
    (= (y ROBOT3) 4.671)
    (= (x ROBOT4) 2.007)
    (= (y ROBOT4) 3.374)
    (= (x ROBOT5) 1.679)
    (= (y ROBOT5) 4.473)
    (= (x ROBOT6) 3.003)
    (= (y ROBOT6) 1.711)
    (= (x TARGET) 1.228)
    (= (y TARGET) 4.970)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
    )
  )
)
