(define (problem p06-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 1.675)
    (= (y ROBOT1) 4.451)
    (= (x ROBOT2) 2.153)
    (= (y ROBOT2) 2.369)
    (= (x ROBOT3) 0.110)
    (= (y ROBOT3) 1.053)
    (= (x ROBOT4) 3.151)
    (= (y ROBOT4) 3.818)
    (= (x ROBOT5) 1.528)
    (= (y ROBOT5) 4.083)
    (= (x ROBOT6) 3.273)
    (= (y ROBOT6) 0.158)
    (= (x TARGET) 3.295)
    (= (y TARGET) 4.021)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
    )
  )
)
