(define (problem p06-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 2.961)
    (= (y ROBOT1) 0.189)
    (= (x ROBOT2) 1.087)
    (= (y ROBOT2) 1.920)
    (= (x ROBOT3) 1.688)
    (= (y ROBOT3) 1.865)
    (= (x ROBOT4) 1.554)
    (= (y ROBOT4) 1.537)
    (= (x ROBOT5) 2.371)
    (= (y ROBOT5) 0.773)
    (= (x ROBOT6) 0.536)
    (= (y ROBOT6) 4.492)
    (= (x TARGET) 3.026)
    (= (y TARGET) 2.641)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
    )
  )
)
