(define (problem p06-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 3.217)
    (= (y ROBOT1) 4.882)
    (= (x ROBOT2) 0.897)
    (= (y ROBOT2) 2.143)
    (= (x ROBOT3) 3.454)
    (= (y ROBOT3) 4.893)
    (= (x ROBOT4) 3.830)
    (= (y ROBOT4) 2.301)
    (= (x ROBOT5) 4.548)
    (= (y ROBOT5) 3.777)
    (= (x ROBOT6) 1.644)
    (= (y ROBOT6) 1.871)
    (= (x TARGET) 1.413)
    (= (y TARGET) 4.629)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
    )
  )
)
