(define (problem p07-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 3.250)
    (= (y ROBOT1) 2.049)
    (= (x ROBOT2) 3.371)
    (= (y ROBOT2) 0.495)
    (= (x ROBOT3) 2.694)
    (= (y ROBOT3) 3.086)
    (= (x ROBOT4) 3.735)
    (= (y ROBOT4) 4.591)
    (= (x ROBOT5) 0.298)
    (= (y ROBOT5) 3.210)
    (= (x ROBOT6) 2.400)
    (= (y ROBOT6) 1.366)
    (= (x ROBOT7) 2.477)
    (= (y ROBOT7) 1.318)
    (= (x TARGET) 2.897)
    (= (y TARGET) 4.995)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
    )
  )
)
