(define (problem p07-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 0.823)
    (= (y ROBOT1) 4.541)
    (= (x ROBOT2) 4.586)
    (= (y ROBOT2) 1.150)
    (= (x ROBOT3) 4.950)
    (= (y ROBOT3) 3.518)
    (= (x ROBOT4) 0.239)
    (= (y ROBOT4) 4.354)
    (= (x ROBOT5) 2.136)
    (= (y ROBOT5) 2.123)
    (= (x ROBOT6) 2.254)
    (= (y ROBOT6) 1.152)
    (= (x ROBOT7) 4.614)
    (= (y ROBOT7) 3.557)
    (= (x TARGET) 0.638)
    (= (y TARGET) 3.422)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
    )
  )
)
