(define (problem p07-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 1.302)
    (= (y ROBOT1) 3.548)
    (= (x ROBOT2) 3.755)
    (= (y ROBOT2) 1.814)
    (= (x ROBOT3) 3.269)
    (= (y ROBOT3) 2.946)
    (= (x ROBOT4) 4.396)
    (= (y ROBOT4) 2.499)
    (= (x ROBOT5) 1.942)
    (= (y ROBOT5) 3.113)
    (= (x ROBOT6) 3.851)
    (= (y ROBOT6) 3.394)
    (= (x ROBOT7) 1.960)
    (= (y ROBOT7) 2.918)
    (= (x TARGET) 3.793)
    (= (y TARGET) 4.090)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
    )
  )
)
