(define (problem p07-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 3.689)
    (= (y ROBOT1) 0.904)
    (= (x ROBOT2) 2.378)
    (= (y ROBOT2) 2.619)
    (= (x ROBOT3) 1.401)
    (= (y ROBOT3) 2.781)
    (= (x ROBOT4) 0.469)
    (= (y ROBOT4) 0.704)
    (= (x ROBOT5) 1.852)
    (= (y ROBOT5) 4.054)
    (= (x ROBOT6) 4.440)
    (= (y ROBOT6) 1.401)
    (= (x ROBOT7) 4.505)
    (= (y ROBOT7) 4.657)
    (= (x TARGET) 4.697)
    (= (y TARGET) 3.304)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
    )
  )
)
