(define (problem p07-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_target TARGET)
    (= (x ROBOT1) 3.059)
    (= (y ROBOT1) 0.437)
    (= (x ROBOT2) 1.705)
    (= (y ROBOT2) 0.352)
    (= (x ROBOT3) 1.843)
    (= (y ROBOT3) 1.836)
    (= (x ROBOT4) 0.283)
    (= (y ROBOT4) 0.360)
    (= (x ROBOT5) 2.191)
    (= (y ROBOT5) 4.924)
    (= (x ROBOT6) 1.461)
    (= (y ROBOT6) 4.610)
    (= (x ROBOT7) 0.581)
    (= (y ROBOT7) 4.078)
    (= (x TARGET) 0.996)
    (= (y TARGET) 4.491)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
    )
  )
)
