(define (problem p08-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 1.239)
    (= (y ROBOT1) 0.623)
    (= (x ROBOT2) 3.939)
    (= (y ROBOT2) 1.723)
    (= (x ROBOT3) 0.814)
    (= (y ROBOT3) 3.859)
    (= (x ROBOT4) 3.642)
    (= (y ROBOT4) 1.248)
    (= (x ROBOT5) 3.667)
    (= (y ROBOT5) 4.298)
    (= (x ROBOT6) 2.695)
    (= (y ROBOT6) 4.018)
    (= (x ROBOT7) 1.639)
    (= (y ROBOT7) 3.990)
    (= (x ROBOT8) 3.952)
    (= (y ROBOT8) 4.112)
    (= (x TARGET) 1.985)
    (= (y TARGET) 1.975)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
    )
  )
)
