(define (problem p08-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 1.686)
    (= (y ROBOT1) 0.333)
    (= (x ROBOT2) 1.419)
    (= (y ROBOT2) 2.165)
    (= (x ROBOT3) 2.728)
    (= (y ROBOT3) 0.523)
    (= (x ROBOT4) 2.477)
    (= (y ROBOT4) 4.980)
    (= (x ROBOT5) 3.519)
    (= (y ROBOT5) 4.496)
    (= (x ROBOT6) 3.407)
    (= (y ROBOT6) 0.857)
    (= (x ROBOT7) 2.277)
    (= (y ROBOT7) 1.000)
    (= (x ROBOT8) 3.044)
    (= (y ROBOT8) 0.249)
    (= (x TARGET) 1.963)
    (= (y TARGET) 0.589)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
    )
  )
)
