(define (problem p08-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 4.427)
    (= (y ROBOT1) 4.159)
    (= (x ROBOT2) 1.831)
    (= (y ROBOT2) 3.732)
    (= (x ROBOT3) 2.722)
    (= (y ROBOT3) 3.631)
    (= (x ROBOT4) 3.582)
    (= (y ROBOT4) 3.526)
    (= (x ROBOT5) 2.166)
    (= (y ROBOT5) 4.873)
    (= (x ROBOT6) 3.264)
    (= (y ROBOT6) 2.584)
    (= (x ROBOT7) 1.485)
    (= (y ROBOT7) 2.118)
    (= (x ROBOT8) 4.933)
    (= (y ROBOT8) 1.943)
    (= (x TARGET) 2.716)
    (= (y TARGET) 1.622)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
    )
  )
)
