(define (problem p08-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_target TARGET)
    (= (x ROBOT1) 3.491)
    (= (y ROBOT1) 1.012)
    (= (x ROBOT2) 2.698)
    (= (y ROBOT2) 2.497)
    (= (x ROBOT3) 0.738)
    (= (y ROBOT3) 2.708)
    (= (x ROBOT4) 1.929)
    (= (y ROBOT4) 2.024)
    (= (x ROBOT5) 3.655)
    (= (y ROBOT5) 1.966)
    (= (x ROBOT6) 4.136)
    (= (y ROBOT6) 4.689)
    (= (x ROBOT7) 0.881)
    (= (y ROBOT7) 0.862)
    (= (x ROBOT8) 1.949)
    (= (y ROBOT8) 3.285)
    (= (x TARGET) 0.470)
    (= (y TARGET) 0.406)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
    )
  )
)
