(define (problem p8)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_target TARGET)
    (= (x ROBOT1) 0.0)
    (= (y ROBOT1) 1.0)
    (= (x ROBOT2) 2.0)
    (= (y ROBOT2) 9.0)
    (= (x TARGET) 0.0)
    (= (y TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
    )
  )
)
