(define (problem p09-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 3.636)
    (= (y ROBOT1) 3.779)
    (= (x ROBOT2) 3.540)
    (= (y ROBOT2) 2.839)
    (= (x ROBOT3) 1.229)
    (= (y ROBOT3) 1.608)
    (= (x ROBOT4) 3.121)
    (= (y ROBOT4) 1.154)
    (= (x ROBOT5) 4.150)
    (= (y ROBOT5) 0.759)
    (= (x ROBOT6) 0.484)
    (= (y ROBOT6) 3.665)
    (= (x ROBOT7) 2.544)
    (= (y ROBOT7) 1.158)
    (= (x ROBOT8) 2.187)
    (= (y ROBOT8) 4.954)
    (= (x ROBOT9) 0.832)
    (= (y ROBOT9) 2.799)
    (= (x TARGET) 0.688)
    (= (y TARGET) 2.583)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
    )
  )
)
