(define (problem p09-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 4.843)
    (= (y ROBOT1) 4.937)
    (= (x ROBOT2) 4.241)
    (= (y ROBOT2) 4.433)
    (= (x ROBOT3) 0.536)
    (= (y ROBOT3) 2.551)
    (= (x ROBOT4) 0.305)
    (= (y ROBOT4) 1.439)
    (= (x ROBOT5) 4.712)
    (= (y ROBOT5) 4.476)
    (= (x ROBOT6) 3.212)
    (= (y ROBOT6) 4.705)
    (= (x ROBOT7) 3.882)
    (= (y ROBOT7) 3.506)
    (= (x ROBOT8) 4.663)
    (= (y ROBOT8) 1.017)
    (= (x ROBOT9) 4.017)
    (= (y ROBOT9) 2.359)
    (= (x TARGET) 3.116)
    (= (y TARGET) 2.324)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
    )
  )
)
