(define (problem p09-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 2.695)
    (= (y ROBOT1) 1.080)
    (= (x ROBOT2) 0.402)
    (= (y ROBOT2) 1.419)
    (= (x ROBOT3) 2.886)
    (= (y ROBOT3) 3.802)
    (= (x ROBOT4) 1.940)
    (= (y ROBOT4) 3.841)
    (= (x ROBOT5) 3.648)
    (= (y ROBOT5) 0.172)
    (= (x ROBOT6) 0.010)
    (= (y ROBOT6) 0.341)
    (= (x ROBOT7) 3.918)
    (= (y ROBOT7) 0.883)
    (= (x ROBOT8) 4.872)
    (= (y ROBOT8) 1.937)
    (= (x ROBOT9) 0.187)
    (= (y ROBOT9) 2.044)
    (= (x TARGET) 3.600)
    (= (y TARGET) 4.260)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
    )
  )
)
