(define (problem p09-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 3.899)
    (= (y ROBOT1) 1.521)
    (= (x ROBOT2) 4.736)
    (= (y ROBOT2) 1.350)
    (= (x ROBOT3) 1.748)
    (= (y ROBOT3) 2.294)
    (= (x ROBOT4) 2.409)
    (= (y ROBOT4) 1.262)
    (= (x ROBOT5) 2.496)
    (= (y ROBOT5) 2.235)
    (= (x ROBOT6) 0.353)
    (= (y ROBOT6) 4.160)
    (= (x ROBOT7) 1.331)
    (= (y ROBOT7) 2.917)
    (= (x ROBOT8) 1.709)
    (= (y ROBOT8) 1.159)
    (= (x ROBOT9) 2.231)
    (= (y ROBOT9) 1.538)
    (= (x TARGET) 3.644)
    (= (y TARGET) 1.522)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
    )
  )
)
