(define (problem p09-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 2.888)
    (= (y ROBOT1) 2.474)
    (= (x ROBOT2) 1.872)
    (= (y ROBOT2) 3.171)
    (= (x ROBOT3) 0.030)
    (= (y ROBOT3) 0.044)
    (= (x ROBOT4) 0.581)
    (= (y ROBOT4) 0.867)
    (= (x ROBOT5) 3.850)
    (= (y ROBOT5) 4.141)
    (= (x ROBOT6) 2.888)
    (= (y ROBOT6) 0.423)
    (= (x ROBOT7) 2.291)
    (= (y ROBOT7) 3.063)
    (= (x ROBOT8) 4.859)
    (= (y ROBOT8) 4.140)
    (= (x ROBOT9) 2.081)
    (= (y ROBOT9) 0.819)
    (= (x TARGET) 3.020)
    (= (y TARGET) 3.897)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
    )
  )
)
