(define (problem p10-2)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 3.832)
    (= (y ROBOT1) 0.194)
    (= (x ROBOT2) 1.030)
    (= (y ROBOT2) 3.246)
    (= (x ROBOT3) 0.371)
    (= (y ROBOT3) 2.082)
    (= (x ROBOT4) 4.324)
    (= (y ROBOT4) 4.467)
    (= (x ROBOT5) 4.209)
    (= (y ROBOT5) 1.566)
    (= (x ROBOT6) 4.153)
    (= (y ROBOT6) 1.717)
    (= (x ROBOT7) 3.038)
    (= (y ROBOT7) 2.661)
    (= (x ROBOT8) 2.153)
    (= (y ROBOT8) 1.286)
    (= (x ROBOT9) 4.865)
    (= (y ROBOT9) 2.687)
    (= (x ROBOT10) 2.263)
    (= (y ROBOT10) 1.899)
    (= (x TARGET) 4.932)
    (= (y TARGET) 2.654)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
      (= (x ROBOT10) (x TARGET))
      (= (y ROBOT10) (y TARGET))
    )
  )
)
