(define (problem p10-1)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 3.656)
    (= (y ROBOT1) 1.141)
    (= (x ROBOT2) 2.931)
    (= (y ROBOT2) 0.873)
    (= (x ROBOT3) 4.679)
    (= (y ROBOT3) 4.184)
    (= (x ROBOT4) 2.639)
    (= (y ROBOT4) 4.693)
    (= (x ROBOT5) 0.297)
    (= (y ROBOT5) 3.230)
    (= (x ROBOT6) 2.570)
    (= (y ROBOT6) 2.395)
    (= (x ROBOT7) 1.254)
    (= (y ROBOT7) 2.729)
    (= (x ROBOT8) 3.631)
    (= (y ROBOT8) 3.781)
    (= (x ROBOT9) 1.873)
    (= (y ROBOT9) 0.044)
    (= (x ROBOT10) 3.696)
    (= (y ROBOT10) 1.175)
    (= (x TARGET) 3.576)
    (= (y TARGET) 2.772)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
      (= (x ROBOT10) (x TARGET))
      (= (y ROBOT10) (y TARGET))
    )
  )
)
