(define (problem p10-3)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 0.386)
    (= (y ROBOT1) 2.145)
    (= (x ROBOT2) 3.967)
    (= (y ROBOT2) 4.813)
    (= (x ROBOT3) 4.025)
    (= (y ROBOT3) 1.361)
    (= (x ROBOT4) 1.961)
    (= (y ROBOT4) 2.599)
    (= (x ROBOT5) 3.836)
    (= (y ROBOT5) 0.319)
    (= (x ROBOT6) 4.805)
    (= (y ROBOT6) 1.004)
    (= (x ROBOT7) 2.054)
    (= (y ROBOT7) 0.419)
    (= (x ROBOT8) 0.498)
    (= (y ROBOT8) 1.668)
    (= (x ROBOT9) 4.174)
    (= (y ROBOT9) 1.869)
    (= (x ROBOT10) 4.729)
    (= (y ROBOT10) 2.441)
    (= (x TARGET) 1.916)
    (= (y TARGET) 0.886)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
      (= (x ROBOT10) (x TARGET))
      (= (y ROBOT10) (y TARGET))
    )
  )
)
