(define (problem p10-5)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 1.117)
    (= (y ROBOT1) 1.371)
    (= (x ROBOT2) 1.037)
    (= (y ROBOT2) 3.503)
    (= (x ROBOT3) 3.529)
    (= (y ROBOT3) 0.447)
    (= (x ROBOT4) 2.290)
    (= (y ROBOT4) 1.659)
    (= (x ROBOT5) 1.810)
    (= (y ROBOT5) 4.137)
    (= (x ROBOT6) 1.843)
    (= (y ROBOT6) 3.192)
    (= (x ROBOT7) 2.679)
    (= (y ROBOT7) 2.582)
    (= (x ROBOT8) 1.163)
    (= (y ROBOT8) 3.051)
    (= (x ROBOT9) 1.407)
    (= (y ROBOT9) 0.754)
    (= (x ROBOT10) 0.286)
    (= (y ROBOT10) 3.412)
    (= (x TARGET) 1.758)
    (= (y TARGET) 2.170)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
      (= (x ROBOT10) (x TARGET))
      (= (y ROBOT10) (y TARGET))
    )
  )
)
