(define (problem p10-4)
  (:domain got_to)

  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 ROBOT10 - robot TARGET - target)

  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_robot ROBOT10)
    (is_target TARGET)
    (= (x ROBOT1) 2.920)
    (= (y ROBOT1) 2.291)
    (= (x ROBOT2) 0.243)
    (= (y ROBOT2) 2.762)
    (= (x ROBOT3) 0.708)
    (= (y ROBOT3) 4.931)
    (= (x ROBOT4) 4.813)
    (= (y ROBOT4) 0.445)
    (= (x ROBOT5) 4.425)
    (= (y ROBOT5) 1.685)
    (= (x ROBOT6) 4.224)
    (= (y ROBOT6) 0.715)
    (= (x ROBOT7) 2.125)
    (= (y ROBOT7) 0.385)
    (= (x ROBOT8) 2.967)
    (= (y ROBOT8) 0.797)
    (= (x ROBOT9) 4.821)
    (= (y ROBOT9) 4.929)
    (= (x ROBOT10) 3.410)
    (= (y ROBOT10) 3.962)
    (= (x TARGET) 2.893)
    (= (y TARGET) 0.852)
  )

  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
      (= (x ROBOT10) (x TARGET))
      (= (y ROBOT10) (y TARGET))
    )
  )
)
