(define (problem p12)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_target TARGET)
    (= (x ROBOT1) 1.0)
    (= (y ROBOT1) 10.0)
    (= (x ROBOT2) 4.0)
    (= (y ROBOT2) 10.0)
    (= (x ROBOT3) 8.0)
    (= (y ROBOT3) 1.0)
    (= (x TARGET) 0.0)
    (= (y TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
    )
  )
)
