(define (problem p23)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_target TARGET)
    (= (x ROBOT1) 0.0)
    (= (y ROBOT1) 9.0)
    (= (x ROBOT2) 8.0)
    (= (y ROBOT2) 4.0)
    (= (x ROBOT3) 6.0)
    (= (y ROBOT3) 10.0)
    (= (x ROBOT4) 8.0)
    (= (y ROBOT4) 0.0)
    (= (x ROBOT5) 7.0)
    (= (y ROBOT5) 10.0)
    (= (x TARGET) 0.0)
    (= (y TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
    )
  )
)
