(define (problem p27)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_target TARGET)
    (= (x ROBOT1) 0.0)
    (= (y ROBOT1) 7.0)
    (= (x ROBOT2) 7.0)
    (= (y ROBOT2) 10.0)
    (= (x ROBOT3) 1.0)
    (= (y ROBOT3) 5.0)
    (= (x ROBOT4) 7.0)
    (= (y ROBOT4) 7.0)
    (= (x ROBOT5) 9.0)
    (= (y ROBOT5) 2.0)
    (= (x ROBOT6) 1.0)
    (= (y ROBOT6) 3.0)
    (= (x TARGET) 0.0)
    (= (y TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
    )
  )
)
