(define (problem p43)
  (:domain got_to)
  (:objects ROBOT1 ROBOT2 ROBOT3 ROBOT4 ROBOT5 ROBOT6 ROBOT7 ROBOT8 ROBOT9 - robot TARGET - target)
  (:init
    (is_robot ROBOT1)
    (is_robot ROBOT2)
    (is_robot ROBOT3)
    (is_robot ROBOT4)
    (is_robot ROBOT5)
    (is_robot ROBOT6)
    (is_robot ROBOT7)
    (is_robot ROBOT8)
    (is_robot ROBOT9)
    (is_target TARGET)
    (= (x ROBOT1) 9.0)
    (= (y ROBOT1) 8.0)
    (= (x ROBOT2) 9.0)
    (= (y ROBOT2) 8.0)
    (= (x ROBOT3) 1.0)
    (= (y ROBOT3) 3.0)
    (= (x ROBOT4) 7.0)
    (= (y ROBOT4) 3.0)
    (= (x ROBOT5) 9.0)
    (= (y ROBOT5) 4.0)
    (= (x ROBOT6) 6.0)
    (= (y ROBOT6) 9.0)
    (= (x ROBOT7) 7.0)
    (= (y ROBOT7) 5.0)
    (= (x ROBOT8) 10.0)
    (= (y ROBOT8) 0.0)
    (= (x ROBOT9) 1.0)
    (= (y ROBOT9) 7.0)
    (= (x TARGET) 0.0)
    (= (y TARGET) 0.0)
  )
  (:goal
    (and
      (= (x ROBOT1) (x TARGET))
      (= (y ROBOT1) (y TARGET))
      (= (x ROBOT2) (x TARGET))
      (= (y ROBOT2) (y TARGET))
      (= (x ROBOT3) (x TARGET))
      (= (y ROBOT3) (y TARGET))
      (= (x ROBOT4) (x TARGET))
      (= (y ROBOT4) (y TARGET))
      (= (x ROBOT5) (x TARGET))
      (= (y ROBOT5) (y TARGET))
      (= (x ROBOT6) (x TARGET))
      (= (y ROBOT6) (y TARGET))
      (= (x ROBOT7) (x TARGET))
      (= (y ROBOT7) (y TARGET))
      (= (x ROBOT8) (x TARGET))
      (= (y ROBOT8) (y TARGET))
      (= (x ROBOT9) (x TARGET))
      (= (y ROBOT9) (y TARGET))
    )
  )
)
