(define (problem delivery1d-002-3)
  (:domain delivery)
  (:objects p1 p2 - package g - gripper t - target)
  (:init
    (= (x p1) 1.0)
    (= (x p2) 2.0)
    (= (x t) 0.0)
    (= (x g) 0.0)
    (is_p p1)
    (is_p p2)
    (is_g g)
    (is_t t)
    (free))
  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))))
)
