(define (problem p04-1)
  (:domain delivery)

  (:objects p1 p2 p3 p4 - package g - gripper t - target)

  (:init
    (= (x p1) 4.961)
    (= (x p2) 8.876)
    (= (x p3) 8.150)
    (= (x p4) 8.176)
    (= (x t) 0.000)
    (= (x g) 9.664)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
  ))
)
