(define (problem p05-5)
  (:domain delivery)

  (:objects p1 p2 p3 p4 p5 - package g - gripper t - target)

  (:init
    (= (x p1) 9.265)
    (= (x p2) 1.123)
    (= (x p3) 0.879)
    (= (x p4) 1.596)
    (= (x p5) 0.502)
    (= (x t) 0.000)
    (= (x g) 4.298)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (= (x p5) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
  ))
)
