(define (problem p05-3)
  (:domain delivery)

  (:objects p1 p2 p3 p4 p5 - package g - gripper t - target)

  (:init
    (= (x p1) 7.752)
    (= (x p2) 0.192)
    (= (x p3) 4.435)
    (= (x p4) 6.394)
    (= (x p5) 0.088)
    (= (x t) 0.000)
    (= (x g) 3.625)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (= (x p5) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
  ))
)
