(define (problem p06-4)
  (:domain delivery)

  (:objects p1 p2 p3 p4 p5 p6 - package g - gripper t - target)

  (:init
    (= (x p1) 8.160)
    (= (x p2) 4.804)
    (= (x p3) 1.260)
    (= (x p4) 1.139)
    (= (x p5) 8.501)
    (= (x p6) 7.115)
    (= (x t) 0.000)
    (= (x g) 5.332)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_p p6)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (= (x p5) (x t))
    (= (x p6) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
    (not (holding p6))
  ))
)
