(define (problem p07-3)
  (:domain delivery)

  (:objects p1 p2 p3 p4 p5 p6 p7 - package g - gripper t - target)

  (:init
    (= (x p1) 2.819)
    (= (x p2) 9.234)
    (= (x p3) 8.036)
    (= (x p4) 6.665)
    (= (x p5) 9.640)
    (= (x p6) 4.854)
    (= (x p7) 7.576)
    (= (x t) 0.000)
    (= (x g) 0.016)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_p p6)
    (is_p p7)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (= (x p5) (x t))
    (= (x p6) (x t))
    (= (x p7) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
    (not (holding p6))
    (not (holding p7))
  ))
)
