(define (problem p08-5)
  (:domain delivery)

  (:objects p1 p2 p3 p4 p5 p6 p7 p8 - package g - gripper t - target)

  (:init
    (= (x p1) 3.867)
    (= (x p2) 5.595)
    (= (x p3) 6.051)
    (= (x p4) 5.283)
    (= (x p5) 5.922)
    (= (x p6) 0.378)
    (= (x p7) 2.174)
    (= (x p8) 3.840)
    (= (x t) 0.000)
    (= (x g) 6.682)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_p p6)
    (is_p p7)
    (is_p p8)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (= (x p5) (x t))
    (= (x p6) (x t))
    (= (x p7) (x t))
    (= (x p8) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
    (not (holding p6))
    (not (holding p7))
    (not (holding p8))
  ))
)
