(define (problem p09-4)
  (:domain delivery)

  (:objects p1 p2 p3 p4 p5 p6 p7 p8 p9 - package g - gripper t - target)

  (:init
    (= (x p1) 6.748)
    (= (x p2) 3.359)
    (= (x p3) 8.945)
    (= (x p4) 6.007)
    (= (x p5) 3.423)
    (= (x p6) 2.826)
    (= (x p7) 9.258)
    (= (x p8) 6.434)
    (= (x p9) 9.765)
    (= (x t) 0.000)
    (= (x g) 4.014)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_p p6)
    (is_p p7)
    (is_p p8)
    (is_p p9)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (x p2) (x t))
    (= (x p3) (x t))
    (= (x p4) (x t))
    (= (x p5) (x t))
    (= (x p6) (x t))
    (= (x p7) (x t))
    (= (x p8) (x t))
    (= (x p9) (x t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
    (not (holding p6))
    (not (holding p7))
    (not (holding p8))
    (not (holding p9))
  ))
)
