(define (problem p10)
    (:domain delivery)
    (:objects p1 p2 p3 p4 p5 p6 - package g - gripper t - target)
    (:init (= (x p1) 0) (= (x p2) 2) (= (x p3) 5) (= (x p4) 1) (= (x p5) 10) (= (x p6) 7) (= (x t) 0) (= (x g) 0)
            (is_p p1) (is_p p2) (is_p p3) (is_p p4) (is_p p5) (is_p p6) (is_g g) (is_t t) (free))
    (:goal (and (= (x p1) (x t)) (= (x p2) (x t)) (= (x p3) (x t)) (= (x p4) (x t)) (= (x p5) (x t)) (= (x p6) (x t)) 
            (free) (not (holding p1)) (not (holding p2)) (not (holding p3)) (not (holding p4)) (not (holding p5)) (not (holding p6)))))