(define (problem p7)
    (:domain delivery)
    (:objects p1 - package g - gripper t - target)
    (:init (= (x p1) 5) (= (x t) 5) (= (x g) 5) (holding p1)
            (is_p p1) (is_g g) (is_t t))
    (:goal (and (= (x p1) (x t)) (free) (not (holding p1)))))