(define (problem p6)
    (:domain delivery)
    (:objects p1 - package g - gripper t - target)
    (:init (= (x p1) 3) (= (x t) 10) (= (x g) 5) (free)
            (is_p p1) (is_g g) (is_t t))
    (:goal (and (= (x p1) (x t)) (free) (not (holding p1)))))