2026-04-28 17:34:58,640 INFO     Policy solves 50 out of 50 problems, unsolved:
2026-04-28 17:34:58,640 INFO     Final policy: 7 rules, 0 transition constraints, 0 state constraints with 4 features: b_nullary(free), n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))), n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))), n_sum_frame(f_primitive_unary(x,0))
Rules:
{ b_nullary(free) ∧ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 }  ⇒  { ¬b_nullary(free) }
{ b_nullary(free) ∧ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 }  ⇒  { ↑n_sum_frame(f_primitive_unary(x,0)) }
{ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 }  ⇒  { ↓n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) ∧ ↑n_sum_frame(f_primitive_unary(x,0)) }
{ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 }  ⇒  { ↓n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) ∧ ↓n_sum_frame(f_primitive_unary(x,0)) }
{ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 ∧ ¬b_nullary(free) }  ⇒  { b_nullary(free) ∧ ↓n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) ∧ ↓n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) ∧ ↓n_sum_frame(f_primitive_unary(x,0)) }
{ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 ∧ ¬b_nullary(free) }  ⇒  { b_nullary(free) ∧ ↓n_sum_frame(f_primitive_unary(x,0)) }
{ n_maximum(f_distance(f_primitive_unary(x,0),f_primitive_unary(x,0))) > 0 ∧ n_maximum(f_distance(f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_p,0)),f_restrict_unary(f_primitive_unary(x,0),c_primitive(is_t,0)))) > 0 ∧ ¬b_nullary(free) }  ⇒  { ↓n_sum_frame(f_primitive_unary(x,0)) }
2026-04-28 17:34:58,640 INFO     Total wall time: 519.35s
2026-04-28 17:34:58,640 INFO     Best policy solver CPU time: 16.65s
2026-04-28 17:34:58,640 INFO     Best policy solver wall time: 10.37s
2026-04-28 17:34:58,640 INFO     Total solver CPU time: 19.41s
2026-04-28 17:34:58,640 INFO     Total CPU time: 525.20s
2026-04-28 17:34:58,640 INFO     Total memory usage: 466.60MB
