(define (problem delivery2d-001-3)
  (:domain delivery)
  (:objects p1 - package g - gripper t - target)
  (:init
    (= (x p1) 9.0)
    (= (y p1) 10.0)
    (= (x t) 0.0)
    (= (y t) 0.0)
    (= (x g) 0.0)
    (= (y g) 0.0)
    (is_p p1)
    (is_g g)
    (is_t t)
    (free))
  (:goal (and
    (= (x p1) (x t))
    (= (y p1) (y t))
    (free)
    (not (holding p1))))
)
