(define (problem delivery2d-002-5)
  (:domain delivery)
  (:objects p1 p2 - package g - gripper t - target)
  (:init
    (= (x p1) 8.0)
    (= (y p1) 1.0)
    (= (x p2) 6.0)
    (= (y p2) 0.0)
    (= (x t) 0.0)
    (= (y t) 0.0)
    (= (x g) 0.0)
    (= (y g) 0.0)
    (is_p p1)
    (is_p p2)
    (is_g g)
    (is_t t)
    (free))
  (:goal (and
    (= (x p1) (x t))
    (= (y p1) (y t))
    (= (x p2) (x t))
    (= (y p2) (y t))
    (free)
    (not (holding p1))
    (not (holding p2))))
)
