(define (problem delivery2d-004-5)
  (:domain delivery)
  (:objects p1 p2 p3 p4 - package g - gripper t - target)
  (:init
    (= (x p1) 3.0)
    (= (y p1) 3.0)
    (= (x p2) 7.0)
    (= (y p2) 5.0)
    (= (x p3) 6.0)
    (= (y p3) 9.0)
    (= (x p4) 4.0)
    (= (y p4) 8.0)
    (= (x t) 0.0)
    (= (y t) 0.0)
    (= (x g) 0.0)
    (= (y g) 0.0)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_g g)
    (is_t t)
    (free))
  (:goal (and
    (= (x p1) (x t))
    (= (y p1) (y t))
    (= (x p2) (x t))
    (= (y p2) (y t))
    (= (x p3) (x t))
    (= (y p3) (y t))
    (= (x p4) (x t))
    (= (y p4) (y t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))))
)
