(define (problem delivery2d-006-3)
  (:domain delivery)
  (:objects p1 p2 p3 p4 p5 p6 - package g - gripper t - target)
  (:init
    (= (x p1) 5.0)
    (= (y p1) 7.0)
    (= (x p2) 6.0)
    (= (y p2) 1.0)
    (= (x p3) 3.0)
    (= (y p3) 3.0)
    (= (x p4) 7.0)
    (= (y p4) 1.0)
    (= (x p5) 1.0)
    (= (y p5) 6.0)
    (= (x p6) 1.0)
    (= (y p6) 2.0)
    (= (x t) 0.0)
    (= (y t) 0.0)
    (= (x g) 0.0)
    (= (y g) 0.0)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_p p6)
    (is_g g)
    (is_t t)
    (free))
  (:goal (and
    (= (x p1) (x t))
    (= (y p1) (y t))
    (= (x p2) (x t))
    (= (y p2) (y t))
    (= (x p3) (x t))
    (= (y p3) (y t))
    (= (x p4) (x t))
    (= (y p4) (y t))
    (= (x p5) (x t))
    (= (y p5) (y t))
    (= (x p6) (x t))
    (= (y p6) (y t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
    (not (holding p6))))
)
