(define (problem delivery2d-009-3)
  (:domain delivery)
  (:objects p1 p2 p3 p4 p5 p6 p7 p8 p9 - package g - gripper t - target)
  (:init
    (= (x p1) 9.0)
    (= (y p1) 8.0)
    (= (x p2) 9.0)
    (= (y p2) 8.0)
    (= (x p3) 1.0)
    (= (y p3) 3.0)
    (= (x p4) 7.0)
    (= (y p4) 3.0)
    (= (x p5) 9.0)
    (= (y p5) 4.0)
    (= (x p6) 6.0)
    (= (y p6) 9.0)
    (= (x p7) 7.0)
    (= (y p7) 5.0)
    (= (x p8) 10.0)
    (= (y p8) 0.0)
    (= (x p9) 1.0)
    (= (y p9) 7.0)
    (= (x t) 0.0)
    (= (y t) 0.0)
    (= (x g) 0.0)
    (= (y g) 0.0)
    (is_p p1)
    (is_p p2)
    (is_p p3)
    (is_p p4)
    (is_p p5)
    (is_p p6)
    (is_p p7)
    (is_p p8)
    (is_p p9)
    (is_g g)
    (is_t t)
    (free))
  (:goal (and
    (= (x p1) (x t))
    (= (y p1) (y t))
    (= (x p2) (x t))
    (= (y p2) (y t))
    (= (x p3) (x t))
    (= (y p3) (y t))
    (= (x p4) (x t))
    (= (y p4) (y t))
    (= (x p5) (x t))
    (= (y p5) (y t))
    (= (x p6) (x t))
    (= (y p6) (y t))
    (= (x p7) (x t))
    (= (y p7) (y t))
    (= (x p8) (x t))
    (= (y p8) (y t))
    (= (x p9) (x t))
    (= (y p9) (y t))
    (free)
    (not (holding p1))
    (not (holding p2))
    (not (holding p3))
    (not (holding p4))
    (not (holding p5))
    (not (holding p6))
    (not (holding p7))
    (not (holding p8))
    (not (holding p9))))
)
