(define (problem p02-2)
  (:domain delivery)

  (:objects p1 p2 - package g - gripper t - target)

  (:init
    (= (x p1) 2.662)
    (= (y p1) 9.300)
    (= (x p2) 7.001)
    (= (y p2) 1.058)
    (= (x t) 0.000)
    (= (y t) 0.000)
    (= (x g) 4.303)
    (= (y g) 2.272)
    (is_p p1)
    (is_p p2)
    (is_g g)
    (is_t t)
    (free)
  )

  (:goal (and
    (= (x p1) (x t))
    (= (y p1) (y t))
    (= (x p2) (x t))
    (= (y p2) (y t))
    (free)
    (not (holding p1))
    (not (holding p2))
  ))
)
