(define (problem p3)
    (:domain delivery)
    (:objects p1 p2 - package g - gripper t - target)
    (:init (= (x p1) 3) (= (y p1) 1) 
            (= (x p2) 3) (= (y p2) 1) 
            (= (x t) 2) (= (y t) 1)
            (= (x g) 2) (= (y g) 1) 
            (free) (is_p p1) (is_p p2) (is_g g) (is_t t))
    (:goal (and (= (x p1) (x t)) (= (y p1) (y t)) 
            (= (x p2) (x t)) (= (y p2) (y t)) 
            (free) (not (holding p1)) (not (holding p2)))))