(define (problem p1)
    (:domain delivery)
    (:objects p1 - package g - gripper t - target)
    (:init (= (x p1) 3) (= (y p1) 1) 
            (= (x t) 0) (= (y t) 0)
            (= (x g) 5) (= (y g) 2) 
            (free) (is_p p1) (is_g g) (is_t t))
    (:goal (and (= (x p1) (x t)) (= (y p1) (y t)) 
            (free) (not (holding p1)))))