(define (problem p5)
    (:domain delivery)
    (:objects p1 p2 p3 p4 - package g - gripper t - target)
    (:init (= (x p1) 3) (= (y p1) 1) 
            (= (x p2) 1) (= (y p2) 1) 
            (= (x p3) 2) (= (y p3) 0) 
            (= (x p4) 3) (= (y p4) 2) 
            (= (x t) 2) (= (y t) 1)
            (= (x g) 2) (= (y g) 1) 
            (free) (is_p p1) (is_p p2) (is_p p3) (is_p p4) (is_g g) (is_t t))
    (:goal (and (= (x p1) (x t)) (= (y p1) (y t)) 
            (= (x p2) (x t)) (= (y p2) (y t)) 
            (= (x p3) (x t)) (= (y p3) (y t)) 
            (= (x p4) (x t)) (= (y p4) (y t)) 
            (free) (not (holding p1)) (not (holding p2)) (not (holding p3)) (not (holding p4)))))